apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::243227082971:role/UdacityFlaskDeployCBKubectlRole
      username: build   
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::243227082971:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1F8RYP0Q2FX8E
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-15T11:27:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1247"
  uid: ec6ae9c7-68c3-41e0-b4c2-04c6f3f4ee52
